numero = (5, 8, 12, 8, 7, 8, 3)
print('tupla original', numero)
print('Tamanho da tupla: ', len(numero))
print('Indice número 2: ', numero[2])
print('Slicing do 2 ao 5: ', numero[2:5])
print('Quantas vezes o "8" é repetido: ', numero.count(8))
print('Primeira ocorrência do número "7": ', numero.index(7))
min_tupla=min(numero)
print('Mostra o mínimo da tupla: ', min_tupla)
max_tupla=max(numero)
print('Mostra o número máximo da tupla: ', max_tupla)
sum_tupla=sum(numero)
print('Mostra a soma da tupla: ', sum_tupla)
print('mostra a tupla em ordem: ', sorted(numero))
print('Mostra  se um número está na tupla: ', 4 in numero)
numero2 = (15, 20)
tupla_concatenada = numero + numero2
print('Resultado da concatenação de duas tuplas1: ', tupla_concatenada)
print('Multiplicação de uma tupla: ', numero * 2)